### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#11]
# ToDos

- [ ] Set page titles
- [ ] [Custom 403, 404, 500 pages](https://learndjango.com/tutorials/customizing-django-404-and-500-error-pages)
- [ ] Optimise form field rendering ([5.0](https://fly.io/django-beats/new-goodies-in-django-50/#form-field-group-rendering))
- [x] Drop unnecessary messages (e.g. "user signed in")
- Settings page
    - [x] Manage Feeds – Link to feed from entry count
    - [x] Tabs – Add icons (like on GitHub)
- Index page 
    - [x] Remove `dark:` classes
    - [x] App title – add RSS icon as logo placeholder
- 1st column
    - [ ] Make 1st column wider 
    - [x] Hide scrollbar
    - [x] Icons for feeds
    - [x] Smart feeds – make all the row clickable as anchor
    - [x] Hide unread badge if there's no unread entries
    - [x] Feeds – Add "cog" icon
    - [x] Hide total number of entries in all, read, favorites
    - [x] Unread feed – make number of entries teal
- 2nd column 
    - [ ] Navbar - Add button with link to feed's web site
    - [ ] Feed Item – Style Favorite items
    - [x] Navbar - Add cog button with link to feed update page
    - [x] Feed Item – Add `object-cover` class to feed image
    - [x] Feed Item – Show site favicon if there's no feed image
- 3rd column
    - [ ] Add back/forth buttons on large screens
    - [ ] Show image from page meta, if there's no images in content and the text is short or absent
    - [x] Make image in top right corner clickable
- "Update feed" page
    - [x] Add "Go To Feed" button with link to feed detail view
    - [x] Link to web site (target = blank)
    - [x] Link to image url (target = blank)
