### ISSUE TITLE
Mark all entries in feed as read feature

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#15]
Add button in 2nd column to mark all entries in open feed as read.

## ToDos

- [x] Add button to column header
- [x] Create service function
- [x] Create endpoint
- [x] Wire up front and back
- [x] Tests!
