### ISSUE TITLE
Manage Feeds

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#18]
## ToDos

- [x] List all existing feeds on Settings/Feeds tab with links to update views
- [x] Update view for Feed
- [x] Tests for update view
- [x] Delete view for Feed
- [x] Tests for delete view
