### ISSUE TITLE
User Profile page

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#20]
## ToDos

- [x] Profile Update view
- [x] Template layout
- [x] Wire up template and view
- [x] Tests!
- [x] Insert profile picture into main navbar (?)
- [x] Styles for file upload block in the form
