### ISSUE TITLE
Optimise SQL queries in views

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#25]
## ToDos

- [x] Replace `Feed.get_unread_count()` with annotation
    - Feeds list view ±72 queries => 11 queries with no dupes
- [x] Replace `Feed.last_updated()` with annotation
    - Manage feeds view ±120 queries (113 dupes) => 8 queries => 6 queries with no dupes
- [x] Remove `prefetch_related("entries")` in `get_all_feeds`:
    - Feeds list view: 11 q/138 ms => 10 q/51 ms!
    - Settings / Feeds tab: 6 q/123 ms => 5 q/35 ms! (+ use annotation with `total_entry_count`)
- [x] Annotate queryset with `total_entry_count` in `get_all_feeds()`
- [x] Use `update()` in `mark_entry_as_read()`
- [x] Use `update()` in `mark_feed_as_read()`
- [ ] Replace `selectors.get_unread_entry_count()` (for Smart Feeds) with annotation
