### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#3]
# ToDos

- [x] Basic tests for `feeds` app
- [x] GitHub Action to run tests on each push
- [x] Run tests before Deploy action
