### ISSUE TITLE
Advanced Celery

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#32]
## ToDos

- [ ] Add backend
- [ ] [Configure Logs](https://testdriven.io/blog/django-and-celery/#celery-logs)
- [ ] [Install Flower Dashboard](https://testdriven.io/blog/django-and-celery/#flower-dashboard)
- [ ] [Configure Retrying](https://testdriven.io/blog/retrying-failed-celery-tasks/#solution-2-task-retry-decorator)
