### ISSUE TITLE
Refactor `services` code

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#39]
## ToDos

- [x]  Rename internal functions with underscore prefixes
- [x]  Do not return null, use custom exceptions
- [x]  Use named tuples, enums
- [x] Refactor `services.feed_update()` using `ThreadPoolExecutor`
