### ISSUE TITLE
Add auth

### ISSUE THREAD

**Issue by hazadus** [hazadus/django-rss-reader#5]
## ToDos

- [x] Install `django-allauth`
- [x] Create basic login page
- [x] Add logout link to in Feeds column header
- [x] Make `feeds` views only available to signed in user, modify tests
- [x] Filter all data by `request.user`
- [x] Display errors on login page
- [x] Create sign up page
